[tool.black]
target_version = ["py310"]
line-length = 79

[tool.mypy]
ignore_missing_imports = true
show_error_codes = true
python_version = "3.10"

[tool.isort]
profile = "black"
lines_between_sections = 1
lines_between_types = 1
line_length = 79
multi_line_output = 3
sections = ['FUTURE', 'STDLIB', 'THIRDPARTY', 'FIRSTPARTY', 'LOCALFOLDER']

[tool.flake8]
max-line-length = 79
extend-ignore = "E203, W503, E722"
max-complexity = 10

[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "$version"
version_scheme = "semver"
version_provider = "pep621"
update_changelog_on_bump = true
major_version_zero = true
